### ISSUE TITLE
Update readme (.md for github and .txt for wp.org)

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/WDS-RSS-Post-Aggregator#1]

**Comment by jtsternberg** [comment]
Let's get all who are in the commit history in the contributors list: https://github.com/WebDevStudios/RSS-Post-Aggregator/commits/master

**Comment by JayWood** [comment]
I'll leave you to update the .txt contributors how you see fit.  I can't remember if contributors that are in the .txt list will automatically get push perms to the wordpress svn or not.  Also, I don't think everyone's .org username matches their GitHub ( i'm a culprit ).

**Comment by jtsternberg** [comment]
@JayWood no, will not receive push permission. Would be helpful if you could poll the group to get their wp usernames. :)
